name: Create release PR if it doesn't exist

on:
  push:
    branches: ['development']
    paths:
      - "apps/webapp/**/*"

jobs:
  release_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if relaese PR exists
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prs=$(gh pr list \
              --repo "$GITHUB_REPOSITORY" \
              --json baseRefName,headRefName \
              --jq '
                  map(select(.baseRefName == "main" and .headRefName == "development"))
                  | length
              ')
          if ((prs > 0)); then
              echo "exists=true" >> "$GITHUB_OUTPUT"
          fi
      - uses: actions/checkout@v3
      - name: Create pull request
        if: '!steps.check.outputs.exists'
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          source_branch: development
          target_branch: main
          title: Release
          body: ${{ github.event.commits[0].message }}
